title: xlab
author: Rasyad Hanizam
email: a.rasyad@gmx.com
description: > # this means to ignore newlines until "baseurl:"
  Description placer

# social links
twitter_username: jimmyrsyd
github_username:  rasyadhs

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
